package container.trial.initialziers;

import container.trial.AbstractTrialDataContainer;
import container.trial.TrialDataContainer;
import exception.TrialException;

/**
 * Default implementation of {@link IInstanceGetter}.
 *
 * @author MTomczyk
 */
public class DefaultInstanceGetter implements IInstanceGetter
{
    /**
     * The method returns a default instance of SDC ({@link AbstractTrialDataContainer}).
     *
     * @param p params container generated by {@link container.trial.TrialDataContainerFactory} and passed here
     * @return instance of {@link AbstractTrialDataContainer}
     * @throws TrialException the exception can be thrown and passed to GDC
     */
    @Override
    public AbstractTrialDataContainer getInstance(AbstractTrialDataContainer.Params p) throws TrialException
    {
        return new TrialDataContainer(p);
    }
}
