package container.trial.initialziers;

import container.trial.AbstractTrialDataContainer;
import container.trial.TrialDataContainerFactory;
import exception.TrialException;

/**
 * Interface for objects for retrieving instances of {@link AbstractTrialDataContainer}.
 *
 * @author MTomczyk
 */
public interface IInstanceGetter
{
    /**
     * The signature of the method for retrieving instances of {@link AbstractTrialDataContainer}.
     * @param p params container generated by {@link TrialDataContainerFactory} and passed here
     * @return instance of {@link AbstractTrialDataContainer}
     * @throws exception.TrialException the exception can be thrown and passed to GDC
     */
    AbstractTrialDataContainer getInstance(AbstractTrialDataContainer.Params p) throws TrialException;
}
