package phase;

import ea.AbstractPhasesEA;
import ea.EA;
import ea.IEA;
import exception.PhaseException;
import population.Chromosome;
import population.Specimen;
import random.IRandom;

import java.util.ArrayList;

/**
 * A simple implementation of {@link phase.IConstruct} that delivers a convenient means for instantiating the initial
 * population (specimens supplied with decision vectors). It is assumed that the population size equals {@link EA#getPopulationSize()}.
 * Also, it is assumed that the decision vectors are boolean vectors created by an implementation of the auxiliary {@link IConstruct} interface.
 *
 * @author MTomczyk
 */
final public class BoolConstruct extends AbstractConstruct implements IConstruct
{
    /**
     * Supportive interface for delivering (constructing) initial decision vectors (integers).
     */
    public interface IConstruct
    {
        /**
         * The main method's signature.
         *
         * @param R random number generator received from the EA
         * @return initial decision vector
         */
        boolean[] create(IRandom R);
    }

    /**
     * Object responsible for creating initial decision vectors.
     */
    private final IConstruct _constructor;

    /**
     * Parameterized constructor.
     *
     * @param constructor object responsible for creating initial decision vectors
     */
    public BoolConstruct(IConstruct constructor)
    {
        _constructor = constructor;
    }

    /**
     * Creates the initial population. This class instantiates specimens' decision vectors as doubles
     * generated by {@link IConstruct}.
     *
     * @param ea evolutionary algorithm
     * @return specimen array
     * @throws PhaseException the exception can be thrown 
     */
    @Override
    public ArrayList<Specimen> createInitialPopulation(IEA ea) throws PhaseException
    {
        ArrayList<Specimen> S = createSpecimenArray(ea);
        for (Specimen s : S) s.setChromosome(new Chromosome(_constructor.create(ea.getR())));
        return S;
    }
}
